execute_process(COMMAND "${NM}" -n "${ELF}" RESULT_VARIABLE rc OUTPUT_VARIABLE symbols ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Unable to inspect runtime symbols: ${err}")
endif()
function(symbol_offset name output)
  string(REGEX MATCH "([0-9a-fA-F]+) [A-Za-z] ${name}" match "${symbols}")
  if(NOT match)
    message(FATAL_ERROR "Missing runtime symbol ${name}")
  endif()
  set(${output} "0x${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
symbol_offset(maya_fragment_decrypt decrypt)
symbol_offset(maya_fragment_decrypt_root decrypt_root)
symbol_offset(maya_state_mask state_mask)
symbol_offset(maya_state_advance state_advance)
symbol_offset(maya_nucleus_map nucleus_map)
symbol_offset(maya_nucleus_protect nucleus_protect)
symbol_offset(maya_nucleus_unmap nucleus_unmap)
symbol_offset(maya_nucleus_cache_sync nucleus_cache_sync)
symbol_offset(maya_nucleus_thread_lookup nucleus_thread_lookup)
symbol_offset(maya_nucleus_thread_destroy nucleus_thread_destroy)
symbol_offset(maya_derive_legacy_body_key derive_legacy_body_key)
symbol_offset(maya_secure_wipe secure_wipe)
symbol_offset(maya_sha256_digest sha256_digest)
set(v3_symbols "")
if(MAYA_ENABLE_V3)
  symbol_offset(maya_v3_derive_vm_key v3_derive_vm_key)
  symbol_offset(maya_v3_issue_capability v3_issue_capability)
  symbol_offset(maya_v3_validate_capability v3_validate_capability)
  symbol_offset(maya_v3_derive_shard_key v3_derive_shard_key)
  string(APPEND v3_symbols "inline constexpr uint64_t v3_derive_vm_key=${v3_derive_vm_key};\ninline constexpr uint64_t v3_issue_capability=${v3_issue_capability};\ninline constexpr uint64_t v3_validate_capability=${v3_validate_capability};\ninline constexpr uint64_t v3_derive_shard_key=${v3_derive_shard_key};\n")
else()
  string(APPEND v3_symbols "inline constexpr uint64_t v3_derive_vm_key=0;\ninline constexpr uint64_t v3_issue_capability=0;\ninline constexpr uint64_t v3_validate_capability=0;\ninline constexpr uint64_t v3_derive_shard_key=0;\n")
endif()
file(WRITE "${OUTPUT}" "#pragma once\n#include <cstdint>\nnamespace maya::runtime_offsets {\ninline constexpr uint64_t decrypt=${decrypt};\ninline constexpr uint64_t decrypt_root=${decrypt_root};\ninline constexpr uint64_t state_mask=${state_mask};\ninline constexpr uint64_t state_advance=${state_advance};\ninline constexpr uint64_t nucleus_map=${nucleus_map};\ninline constexpr uint64_t nucleus_protect=${nucleus_protect};\ninline constexpr uint64_t nucleus_unmap=${nucleus_unmap};\ninline constexpr uint64_t nucleus_cache_sync=${nucleus_cache_sync};\ninline constexpr uint64_t nucleus_thread_lookup=${nucleus_thread_lookup};\ninline constexpr uint64_t nucleus_thread_destroy=${nucleus_thread_destroy};\ninline constexpr uint64_t derive_legacy_body_key=${derive_legacy_body_key};\ninline constexpr uint64_t secure_wipe=${secure_wipe};\ninline constexpr uint64_t sha256_digest=${sha256_digest};\n${v3_symbols}}\n")
